#import <Foundation/Foundation.h>
#import "WLReservationsResponse.h"
#import "WLReservation.h"
#import "WLErrorResponse.h"
#import "WLReservationRequest.h"
#import "WLApi.h"

/**
* Waitlisted API
* Waitlisted API
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface WLReservationApi: NSObject <WLApi>

extern NSString* kWLReservationApiErrorDomain;
extern NSInteger kWLReservationApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// 
/// Creates a new reservation.
///
/// @param body Reservation Data
/// 
///  code:200 message:"reservation response",
///  code:401 message:"invalid api_key header",
///  code:404 message:"site/reservation not found",
///  code:500 message:"invalid post body"
///
/// @return WLReservationsResponse*
-(NSNumber*) createReservationWithBody: (WLReservation*) body
    completionHandler: (void (^)(WLReservationsResponse* output, NSError* error)) handler;


/// 
/// Delete a reservation.
///
/// @param body Reservation Data
/// 
///  code:200 message:"deleted successfully",
///  code:401 message:"invalid api_key header",
///  code:404 message:"site/reservation not found"
///
/// @return 
-(NSNumber*) deleteReservationWithBody: (WLReservationRequest*) body
    completionHandler: (void (^)(NSError* error)) handler;


/// 
/// Get a reservation.
///
/// @param email Email address
/// 
///  code:200 message:"reservation response",
///  code:404 message:"site/reservation not found"
///
/// @return WLReservationsResponse*
-(NSNumber*) getReservationWithEmail: (NSString*) email
    completionHandler: (void (^)(WLReservationsResponse* output, NSError* error)) handler;



@end
