#import <Foundation/Foundation.h>
#import "WLObject.h"

/**
* Waitlisted API
* Waitlisted API
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol WLReservationsResponse
@end

@interface WLReservationsResponse : WLObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* uuid;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* affiliate;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* referredCount;

@property(nonatomic) NSNumber* position;

@property(nonatomic) NSNumber* totalCount;

@property(nonatomic) NSDate* activatedAt;

@property(nonatomic) NSDate* createdAt;

@end
