#import <Foundation/Foundation.h>
#import "WLObject.h"

/**
* Waitlisted API
* Waitlisted API
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol WLSiteResponse
@end

@interface WLSiteResponse : WLObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* brandColor;

@property(nonatomic) NSString* buttonTextColor;

@property(nonatomic) NSString* customStyles;

@property(nonatomic) NSNumber* askName;

@property(nonatomic) NSString* signupTitle;

@property(nonatomic) NSString* signupCopy;

@property(nonatomic) NSString* positionTitle;

@property(nonatomic) NSString* socialCopy;

@property(nonatomic) NSString* socialMessage;

@property(nonatomic) NSString* domain;

@property(nonatomic) NSString* shareSocialCopy;

@property(nonatomic) NSString* referralCopy;

@property(nonatomic) NSString* checkPositionCopy;

@property(nonatomic) NSString* joinButtonCopy;

@property(nonatomic) NSString* checkReservationCopy;

@property(nonatomic) NSString* emailFieldLabel;

@property(nonatomic) NSString* nameFieldLabel;

@property(nonatomic) NSString* thankYouShareTemplate;

@property(nonatomic) NSNumber* waitlistThreshold;

@property(nonatomic) NSNumber* useCustomThankYou;

@property(nonatomic) NSNumber* hideWaitlist;

@property(nonatomic) NSString* unmetSharedTemplate;

@property(nonatomic) NSNumber* thresholdMet;

@property(nonatomic) NSString* websiteUrl;

@property(nonatomic) NSString* trackingCode;

@property(nonatomic) NSString* customCss;

@property(nonatomic) NSNumber* hideBranding;

@property(nonatomic) NSNumber* totalCount;

@end
